import { LOCALIZATION_KEY_SYSTEM, LOCALIZATION_KEY_SYSTEM_WITH_LANGUAGE } from "./LOCALIZATION_KEY.mjs";

export const TEXTS_EN = Object.freeze({
    [LOCALIZATION_KEY_SYSTEM]: "System",
    [LOCALIZATION_KEY_SYSTEM_WITH_LANGUAGE]: "System ({language})"
});
